CREATE TABLE `appointments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`propertyId` int,
	`leadId` int,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`scheduledAt` timestamp NOT NULL,
	`duration` int NOT NULL DEFAULT 60,
	`status` enum('agendado','confirmado','realizado','cancelado','reagendado') NOT NULL DEFAULT 'agendado',
	`location` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appointments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(100) NOT NULL,
	`cnpj` varchar(18),
	`creci` varchar(50),
	`email` varchar(320),
	`phone` varchar(20),
	`whatsapp` varchar(20),
	`address` text,
	`city` varchar(100),
	`state` varchar(2),
	`zipCode` varchar(10),
	`logoUrl` text,
	`bannerUrl` text,
	`description` text,
	`planId` int,
	`planExpiresAt` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companies_id` PRIMARY KEY(`id`),
	CONSTRAINT `companies_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `interactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`userId` int NOT NULL,
	`type` enum('ligacao','whatsapp','email','visita','reuniao','proposta','nota') NOT NULL,
	`description` text NOT NULL,
	`outcome` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `interactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`assignedUserId` int,
	`propertyId` int,
	`name` varchar(255) NOT NULL,
	`email` varchar(320),
	`phone` varchar(20),
	`whatsapp` varchar(20),
	`source` enum('site','whatsapp','telefone','indicacao','portal','facebook','instagram','google','outro') NOT NULL DEFAULT 'site',
	`sourceDetail` varchar(255),
	`interestType` enum('compra','aluguel','investimento','outro'),
	`budget` decimal(15,2),
	`message` text,
	`stage` enum('novo','contato_inicial','qualificado','visita_agendada','proposta','negociacao','fechado_ganho','fechado_perdido') NOT NULL DEFAULT 'novo',
	`preferredPropertyTypes` json,
	`preferredNeighborhoods` json,
	`minBedrooms` int,
	`maxBedrooms` int,
	`notes` text,
	`lastContactAt` timestamp,
	`nextFollowUpAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`slug` varchar(50) NOT NULL,
	`description` text,
	`price` decimal(10,2) NOT NULL,
	`maxProperties` int NOT NULL,
	`maxUsers` int NOT NULL,
	`maxPhotosPerProperty` int NOT NULL DEFAULT 20,
	`hasAI` boolean NOT NULL DEFAULT false,
	`aiCreditsPerDay` int NOT NULL DEFAULT 0,
	`hasWhatsappIntegration` boolean NOT NULL DEFAULT false,
	`hasPortalIntegration` boolean NOT NULL DEFAULT false,
	`hasCustomDomain` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `plans_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`userId` int NOT NULL,
	`code` varchar(50),
	`title` varchar(255) NOT NULL,
	`slug` varchar(300),
	`description` text,
	`type` enum('casa','apartamento','terreno','comercial','rural','cobertura','flat','kitnet','sobrado','galpao','sala_comercial','loja','outro') NOT NULL,
	`purpose` enum('venda','aluguel','venda_aluguel') NOT NULL,
	`salePrice` decimal(15,2),
	`rentPrice` decimal(15,2),
	`condoFee` decimal(10,2),
	`iptuAnnual` decimal(10,2),
	`address` varchar(255),
	`number` varchar(20),
	`complement` varchar(100),
	`neighborhood` varchar(100),
	`city` varchar(100) NOT NULL,
	`state` varchar(2) NOT NULL,
	`zipCode` varchar(10),
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`totalArea` decimal(10,2),
	`builtArea` decimal(10,2),
	`bedrooms` int DEFAULT 0,
	`suites` int DEFAULT 0,
	`bathrooms` int DEFAULT 0,
	`parkingSpaces` int DEFAULT 0,
	`amenities` json,
	`status` enum('disponivel','reservado','vendido','alugado','inativo') NOT NULL DEFAULT 'disponivel',
	`isHighlight` boolean NOT NULL DEFAULT false,
	`isPublished` boolean NOT NULL DEFAULT true,
	`metaTitle` varchar(70),
	`metaDescription` varchar(160),
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `properties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `property_images` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`url` text NOT NULL,
	`fileKey` varchar(255),
	`caption` varchar(255),
	`order` int NOT NULL DEFAULT 0,
	`isMain` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `property_images_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `site_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`primaryColor` varchar(7) DEFAULT '#0F52BA',
	`secondaryColor` varchar(7) DEFAULT '#50C878',
	`fontFamily` varchar(100) DEFAULT 'Inter',
	`siteTitle` varchar(70),
	`siteDescription` varchar(160),
	`googleAnalyticsId` varchar(50),
	`facebookPixelId` varchar(50),
	`facebookUrl` varchar(255),
	`instagramUrl` varchar(255),
	`linkedinUrl` varchar(255),
	`youtubeUrl` varchar(255),
	`whatsappDefaultMessage` text,
	`customDomain` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `site_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `site_settings_companyId_unique` UNIQUE(`companyId`)
);
--> statement-breakpoint
ALTER TABLE `users` ADD `phone` varchar(20);--> statement-breakpoint
ALTER TABLE `users` ADD `companyId` int;